### ISSUE TITLE
Simulator document missing

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#169]
Jing reports that _coinstac-simulator_ crashes on her machine (devcoin5):

```shell
info: LOCAL testUser1 [16949]: Database consortia .all() attempts: 1
info: LOCAL testUser5 [16968]: Database consortia .all() attempts: 1
info: LOCAL testUser3 [16956]: Saving project
info: LOCAL testUser1 [16949]: Saving project
error: LOCAL testUser2 [16955]: Unhandled Rejection at: Promise Promise {
 <rejected> { [not_found: missing]
 status: 404,
 name: 'not_found',
 message: 'missing',
 error: true,
 reason: 'missing' } } reason:
info: LOCAL testUser5 [16968]: Saving project
/home/jming/decentralized-single-shot-ridge-regression/node_modules/coinstac-simulator/src/boot-locals.js:45
       throw new Error(`Local process exited with code ${code}`);
       ^

Error: Local process exited with code 1
   at ChildProcess.localProcess.on.code (/home/jming/decentralized-single-shot-ridge-regression/node_modules/coinstac-simulator/src/boot-locals.js:45:15)
   at emitTwo (events.js:106:13)
   at ChildProcess.emit (events.js:191:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

This seems to occur with every run.

**Comment by swashcap** [comment]
This problem occurs on a devcoin but not on a MacBook Pro, leading me to believe it's a Node.js child process memory issue.

**Comment by swashcap** [comment]
![simulate-and-htop](https://cloud.githubusercontent.com/assets/1858316/23721942/4cefbde4-03f8-11e7-84cd-cdfe9e71e750.gif)

Looks like the CPU’s quickly at 100% and the memory maybe (probably) hits the maximum (1G, I believe) on a devcoin.

**Comment by swashcap** [comment]
Or, this could be a race condition in the underlying architecture of COINSTAC. Moving this to post-demo as it will derail our demo timeline.
