### ISSUE TITLE
coinstac-simulator can’t simulate more than 4 clients

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#27]
**Problem:** _coinstac-simulator_ errors out when the declarations file contains more than 4 users.

Here’s an example error:

``` shell
error: USER loadTestUser2 [36775]: error: Unhandled Rejection at: Promise Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: 
   TypeError: Cannot read property '_id' of undefined
       at consortiaDB.all.then.then.then.then (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:88:41)
       at runCallback (timers.js:570:20)
       at tryOnImmediate (timers.js:550:5)
       at processImmediate [as _immediateCallback] (timers.js:529:5)
   From previous event:
       at kickoff (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:78:4)
       at process.on (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:132:5)
       at emitTwo (events.js:106:13)
       at process.emit (events.js:191:7)
       at process.nextTick (internal/child_process.js:719:12)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)
       at process._tickCallback (internal/process/next_tick.js:98:9),
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _trace: 
   { Error
       at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/debuggability.js:369:19)
       at Promise._then (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/promise.js:230:17)
       at Promise.then (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/promise.js:123:17)
       at kickoff (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:123:4)
       at process.on (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:132:5)
       at emitTwo (events.js:106:13)
       at process.emit (events.js:191:7)
       at process.nextTick (internal/child_process.js:719:12)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)
       at process._tickCallback (internal/process/next_tick.js:98:9)
       at Async._schedule (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/schedule.js:12:53)
       at Async._queueTick (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/async.js:157:14)
       at AsyncSettlePromises [as settlePromises] (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/async.js:88:10)
       at Promise._fulfill (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/promise.js:632:19)
       at Promise._resolveCallback (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/promise.js:425:57)
       at resolve (/Users/creed/coinstac/packages/coinstac-common/node_modules/bluebird/js/release/thenables.js:73:17) _parent: undefined, _promisesCreated: 0, _length: 1 } } reason: TypeError: Cannot read property '_id' of undefined
    at consortiaDB.all.then.then.then.then (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:88:41)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
From previous event:
    at kickoff (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:78:4)
    at process.on (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-client.js:132:5)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
/Users/creed/coinstac/packages/coinstac-simulator/src/boot-clients.js:35
          if (code) { throw new Error(`user process exited with ${code}`); }
                      ^

Error: user process exited with 1
    at ChildProcess.userProcess.on (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-clients.js:35:29)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
    at new ChildProcess (internal/child_process.js:167:18)
    at exports.spawn (child_process.js:368:15)
    at Object.exports.fork (child_process.js:54:10)
    at Promise (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-clients.js:24:32)
    at Promise.all.usernames.map (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-clients.js:23:14)
    at Array.map (native)
    at bootClients (/Users/creed/coinstac/packages/coinstac-simulator/src/boot-clients.js:22:15)
    at bootDBServer.setup.then.then.then.then.then.then.then.then.then (/Users/creed/coinstac/packages/coinstac-simulator/src/index.js:64:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Object.run (/Users/creed/coinstac/packages/coinstac-simulator/src/index.js:64:6)
    at Object.<anonymous> (/Users/creed/coinstac/packages/coinstac-simulator/src/cli/index.js:9:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by swashcap** [comment]
The `Cannot read property '_id'` error was present when simulating 10, 7, 6 and 5 clients. ??

[--- Commented from Asana.com
#commenter coins
---[aa]

**Comment by swashcap** [comment]
Fortunately, I’m able to run 6 clients using _coinstac-client-core_’s CLI. This tells us the problem lies somewhere in simulator.

![its-working](https://cloud.githubusercontent.com/assets/1858316/17939080/bc157cdc-69dd-11e6-8ad8-1e1f2a7b55bd.gif)

**Comment by swashcap** [comment]
Here’s the error for 5 clients with some logging:

``` shell
info: db server up
info: db seeded consortium=testconsortiumid1472100989371, computation=coinstac-simulator-load-tester@1.0.0
info: compute server up
info: clients up
info: USER loadTestUser0 [3275]: info: Has likely synced: true
info: USER loadTestUser1 [3276]: info: Has likely synced: true
info: USER loadTestUser3 [3278]: info: Has likely synced: true
info: USER loadTestUser2 [3277]: info: Has likely synced: true
info: USER loadTestUser3 [3278]: info:  description=test-default-consortium, label=test-default-consortium, tags=[], users=[loadTestUser0, ladTestUser1, loadTestUser2, loadTestUser3, loadTestUser4], owners=[loadTestUser0, loadTestUser1, loadTestUser2, loadTestUser3, loadTestUser4, _id=testconsortiumid1472100989371, _rev=1-0d5db1d8637b821d7bc244c6c5ce62e4
info: USER loadTestUser4 [3279]: info: Has likely synced: true
info: USER loadTestUser1 [3276]: info:  description=test-default-consortium, label=test-default-consortium, tags=[], users=[loadTestUser0, ladTestUser1, loadTestUser2, loadTestUser3, loadTestUser4], owners=[loadTestUser0, loadTestUser1, loadTestUser2, loadTestUser3, loadTestUser4, _id=testconsortiumid1472100989371, _rev=1-0d5db1d8637b821d7bc244c6c5ce62e4
info: USER loadTestUser4 [3279]: info: 
info: USER loadTestUser0 [3275]: info:  description=test-default-consortium, label=test-default-consortium, tags=[], users=[loadTestUser0, ladTestUser1, loadTestUser2, loadTestUser3, loadTestUser4], owners=[loadTestUser0, loadTestUser1, loadTestUser2, loadTestUser3, loadTestUser4, _id=testconsortiumid1472100989371, _rev=1-0d5db1d8637b821d7bc244c6c5ce62e4
info: USER loadTestUser2 [3277]: info:  description=test-default-consortium, label=test-default-consortium, tags=[], users=[loadTestUser0, ladTestUser1, loadTestUser2, loadTestUser3, loadTestUser4], owners=[loadTestUser0, loadTestUser1, loadTestUser2, loadTestUser3, loadTestUser4, _id=testconsortiumid1472100989371, _rev=1-0d5db1d8637b821d7bc244c6c5ce62e4
error: USER loadTestUser4 [3279]: error: Unhandled Rejection at: Promise Promise {
  _bitField: 18087936,
  _fulfillmentHandler0: 
   TypeError: Cannot read property '_id' of undefined
#...
```

The `info: USER loadTestUser4 [3279]: info:` line [comes from roughly here](https://github.com/MRN-Code/coinstac/blob/c0d0fe2f9a77d930c770a65bd7c92d8efe229b87/packages/coinstac-simulator/src/boot-client.js#L72), indicating that the fifth user doesn’t receive any consortium documents. The affected user appears to change. This smells like a storage layer or transport layer bug.

Also worth noting: every client’s consortia Pouchy instance’s `_hasLikelySynced` property is `true`.

**Comment by swashcap** [comment]
By changing the [port here](https://github.com/MRN-Code/coinstac/blob/c0d0fe2f9a77d930c770a65bd7c92d8efe229b87/packages/coinstac-simulator/src/.pouchdb-server-config.js#L5) and returning `Promise.resolve()` from [this module’s methods](https://github.com/MRN-Code/coinstac/blob/c0d0fe2f9a77d930c770a65bd7c92d8efe229b87/packages/coinstac-simulator/src/boot-db-server.js) I was able to easily use CouchDB as _coinstac-simulator_’s data layer. It appears to work fine with _10 clients_, indicating the problem lies in either [pouchdb/pouchdb-server](https://github.com/pouchdb/pouchdb-server) or [gr2m/spawn-pouchdb-server](https://github.com/gr2m/spawn-pouchdb-server).

**Comment by swashcap** [comment]
Update: I constructed a simple version of _coinstac-simulator_ in [swashcap/silly-pouchdb-server](https://github.com/swashcap/silly-pouchdb-server). Unfortunately, both pouchdb-server and spawn-pouchdb-server are capable of handling 10+ clients, leading me to believe the problem lies in _coinstac-simulator_’s code. ??

[--- Commented from Asana.com
#commenter coins
---[aa]
