### ISSUE TITLE
Simulator: simulator fails with dsne multishot

### ISSUE THREAD

**Issue by deblearn** [trendscenter/coinstac#489]
# Problem
Simulator run failed!
This may be an internal simulator issue
 If you suspect this, please leave an issue on github.com/MRN-Code/coinstac/issues with the error details
TypeError: chunk.charAt is not a function
    at SAXParser.write (/usr/local/lib/node_modules/coinstac-simulator/node_modules/hermit/node_modules/sax/lib/sax.js:917:31)
    at parse (/usr/local/lib/node_modules/coinstac-simulator/node_modules/hermit/lib/parse.js:85:10)
    at hermit (/usr/local/lib/node_modules/coinstac-simulator/node_modules/hermit/hermit.js:12:3)
    at readFile.then.then.then.then.catch (/usr/local/lib/node_modules/coinstac-simulator/bin/coinstac-simulator:221:3)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

# Tasks
My code repository:
https://github.com/hvgazula/dsne-ms_test.git

**Comment by deblearn** [comment]
I was trying to figure it out why this error was occurred. I think it is arising when we are trying to debug the code using "raise Exception". May be the "raise Exception" is not working perfectly.
