### ISSUE TITLE
Ensure computations don't crash the server

### ISSUE THREAD

**Issue by swashcap** [trendscenter/coinstac#79]
We've observed that the multishot computation crashes the server. Error message:

``` shell
error: Server promise rejection { Error: demo2 reports undefined features, but demo1 reports 3 features.
    at opts.userResults.forEach (/coins/coinstac/packages/coinstac-common/node_modules/laplacian-noise-ridge-regression/src/remote.js:21:15)
    at Array.forEach (native)
    at Object.assertUserDatas (/coins/coinstac/packages/coinstac-common/node_modules/laplacian-noise-ridge-regression/src/remote.js:14:22)
    at Object.run (/coins/coinstac/packages/coinstac-common/node_modules/laplacian-noise-ridge-regression/src/remote.js:56:10)
    at JavascriptComputation.fn (/coins/coinstac/packages/coinstac-common/node_modules/laplacian-noise-ridge-regression/src/index.js:54:36)
    at JavascriptComputation.run (/coins/coinstac/packages/coinstac-common/src/models/computation/javascript-computation.js:20:33)
    at tryNext.then.then.then (/coins/coinstac/packages/coinstac-common/src/models/pipeline/pipeline.js:138:31)
From previous event:
    at runQueue.(anonymous function).runQueue.(anonymous function).then (/coins/coinstac/packages/coinstac-common/src/models/pipeline/runner/pool/pipeline-runner-pool.js:554:23)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)
From previous event:
    at RemotePipelineRunnerPool.triggerRunner (/coins/coinstac/packages/coinstac-common/src/models/pipeline/runner/pool/pipeline-runner-pool.js:552:6)
    at RemotePipelineRunnerPool.handleResultChange (/coins/coinstac/packages/coinstac-common/src/models/pipeline/runner/pool/pipeline-runner-pool.js:304:10)
    at DBListener.listener.on (/coins/coinstac/packages/coinstac-common/src/models/pipeline/runner/pool/pipeline-runner-pool.js:407:24)
    at emitOne (events.js:96:13)
    at DBListener.emit (events.js:188:7)
    at Changes.DBListener.changes.pouchy.changes.on.info (/coins/coinstac/packages/coinstac-common/src/models/db-listener.js:30:14)
    at emitOne (events.js:96:13)
    at Changes.emit (events.js:188:7)
    at tryCatchInChangeListener (/coins/coinstac/packages/coinstac-common/node_modules/pouchdb-core/lib/index.js:41:10)
    at Object.Changes.opts.onChange (/coins/coinstac/packages/coinstac-common/node_modules/pouchdb-core/lib/index.js:79:5)
    at Changes.<anonymous> (/coins/coinstac/packages/coinstac-server-core/node_modules/pouchdb-utils/lib/index.js:409:14)
    at emitOne (events.js:96:13)
    at Changes.emit (events.js:188:7)
    at tryCatchInChangeListener (/coins/coinstac/packages/coinstac-common/node_modules/pouchdb-core/lib/index.js:41:10)
    at Object.Changes.opts.onChange (/coins/coinstac/packages/coinstac-common/node_modules/pouchdb-core/lib/index.js:79:5)
    at onGetWinningDoc (/coins/coinstac/packages/coinstac-server-core/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:1319:20)
    at onGetMetadata (/coins/coinstac/packages/coinstac-server-core/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:1337:18)
    at /coins/coinstac/packages/coinstac-server-core/node_modules/pouchdb-adapter-leveldb-core/lib/index.js:1361:9
    at /coins/coinstac/packages/coinstac-server-core/node_modules/sublevel-pouchdb/lib/shell.js:87:12
    at /coins/coinstac/packages/coinstac-server-core/node_modules/sublevel-pouchdb/lib/nut.js:103:19 isRunError: true } _bitField=18087936, isRunError=true, _rejectionHandler0=undefined, _promise0=undefined, _receiver0=undefined, _parent=undefined, _promisesCreated=0, _length=1
info: Shutting down server…
```

This appears to come for [a branch in remote.js](https://github.com/MRN-Code/decentralized-laplacian-ridge-regression/blob/06f324ccf9c41974300674e74664c3a5c260f993/src/remote.js#L18).

**Comment by swashcap** [comment]
For debugging purposes, I’ll add the database state. We're running multishot ridge regression with two users, _demo1_ and _demo2_. It should go for 200 iterations, then stop.

_demo1_’s local result’s `data`:

``` json
{
   "biasedX": [
       [
           31,
           1,
           1
       ],
       [
           62,
           1,
           1
       ],
       [
           61,
           1,
           1
       ],
       [
           57,
           1,
           1
       ],
       [
           44,
           1,
           1
       ],
       [
           41,
           1,
           1
       ],
       [
           33,
           1,
           1
       ],
       [
           48,
           1,
           1
       ],
       [
           43,
           1,
           1
       ],
       [
           18,
           1,
           1
       ],
       [
           27,
           1,
           1
       ],
       [
           45,
           1,
           1
       ],
       [
           43,
           1,
           1
       ],
       [
           37,
           1,
           1
       ],
       [
           28,
           1,
           1
       ],
       [
           40,
           1,
           1
       ],
       [
           27,
           1,
           1
       ],
       [
           58,
           1,
           1
       ],
       [
           44,
           1,
           1
       ],
       [
           30,
           1,
           1
       ],
       [
           25,
           1,
           1
       ],
       [
           64,
           1,
           1
       ],
       [
           65,
           1,
           1
       ],
       [
           29,
           1,
           1
       ],
       [
           38,
           1,
           1
       ],
       [
           62,
           1,
           1
       ],
       [
           50,
           1,
           1
       ],
       [
           44,
           1,
           1
       ],
       [
           43,
           1,
           1
       ],
       [
           64,
           1,
           1
       ],
       [
           30,
           1,
           1
       ],
       [
           46,
           1,
           1
       ],
       [
           48,
           1,
           1
       ],
       [
           36,
           1,
           1
       ],
       [
           57,
           1,
           1
       ],
       [
           48,
           1,
           1
       ],
       [
           53,
           1,
           1
       ],
       [
           48,
           1,
           1
       ],
       [
           19,
           1,
           1
       ],
       [
           63,
           -1,
           1
       ],
       [
           25,
           -1,
           1
       ],
       [
           22,
           -1,
           1
       ],
       [
           21,
           -1,
           1
       ],
       [
           41,
           -1,
           1
       ],
       [
           28,
           -1,
           1
       ],
       [
           60,
           -1,
           1
       ],
       [
           30,
           -1,
           1
       ],
       [
           59,
           -1,
           1
       ],
       [
           28,
           -1,
           1
       ],
       [
           51,
           -1,
           1
       ],
       [
           58,
           -1,
           1
       ],
       [
           58,
           -1,
           1
       ],
       [
           50,
           -1,
           1
       ],
       [
           39,
           -1,
           1
       ],
       [
           19,
           -1,
           1
       ],
       [
           37,
           -1,
           1
       ],
       [
           58,
           -1,
           1
       ],
       [
           24,
           -1,
           1
       ],
       [
           21,
           -1,
           1
       ],
       [
           24,
           -1,
           1
       ],
       [
           35,
           -1,
           1
       ],
       [
           25,
           -1,
           1
       ],
       [
           54,
           -1,
           1
       ],
       [
           48,
           -1,
           1
       ],
       [
           26,
           -1,
           1
       ],
       [
           49,
           -1,
           1
       ],
       [
           38,
           -1,
           1
       ],
       [
           59,
           -1,
           1
       ],
       [
           38,
           -1,
           1
       ],
       [
           32,
           -1,
           1
       ],
       [
           35,
           -1,
           1
       ],
       [
           33,
           -1,
           1
       ]
   ],
   "eta": 0.1,
   "lambda": 0,
   "numFeatures": 3,
   "y": [
       19291.1,
       13879.3,
       10864.6,
       16708.5,
       16282.6,
       19975.8,
       13410.5,
       14805.3,
       15641.4,
       15201.4,
       21155.5,
       14742.3,
       16435.9,
       15839.8,
       16441.5,
       12169.4,
       21068.8,
       16371.9,
       13654,
       12096.8,
       15748.2,
       15894.3,
       15262.1,
       14567.6,
       16379.8,
       22492.5,
       15906.9,
       16315.2,
       15299.2,
       14405,
       13156,
       16052.8,
       15813,
       16732,
       15581.7,
       20001.8,
       15053,
       15510.8,
       21895.8,
       17109.6,
       15221.5,
       14736.9,
       18077.1,
       15776.8,
       14012.6,
       19056.4,
       14384.4,
       13832.1,
       11583.9,
       18571.2,
       19409,
       12088,
       18773.5,
       12407.5,
       14743.8,
       16344.5,
       14809.8,
       15242.8,
       18158.2,
       11120.8,
       25778.5,
       18364.5,
       15697.8,
       16038.5,
       20357.7,
       16700.2,
       14551.8,
       13760,
       18235.8,
       12970.2,
       12966.6,
       13921.8
   ]
}
```

_demo2_’s local result’s `data`:

``` json
{
   "biasedX": [
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ],
       [
           66,
           -1,
           1
       ]
   ],
   "y": [
       16053.9,
       14648.8,
       15110.6,
       13282.4,
       15876.3,
       16682.7,
       14815.6,
       17520.4,
       15842.3,
       13078.9,
       15773,
       16310.2,
       14678.1,
       12165.4,
       14328.9,
       14350.6,
       14170.1,
       13344.7,
       21280.4,
       18648.6,
       21669.6,
       13340.3,
       17200.4,
       13626.9,
       16278.3,
       16119.4,
       16397.8,
       13214.2,
       18189.8,
       14883.6,
       14255.1,
       14739.5,
       16494.8,
       15405.9,
       16631.8,
       14651,
       12479.2,
       16674.1,
       19679.5,
       14142.1,
       19610.2,
       15476.5,
       16994.6,
       11597.4,
       18143.2,
       15423.2,
       14874.2,
       12760.1,
       15206.2,
       14833.4,
       11651.4,
       12809.1,
       14294.2,
       14750.9,
       18196.1,
       16810.1,
       18849.1,
       20596.8,
       16691.9,
       16282.9,
       16348.9,
       17130.5,
       19217,
       16059.8,
       12158.3,
       19942.2,
       17687.9,
       17727.1,
       14232.5,
       13755.5,
       16304.7,
       19084.7,
       15562.8
   ],
   "lGrad": [
       -5481971.006186579,
       48999.403924245664,
       -83060.16676040267
   ],
   "lObj": 403042706.557263
}
```

**Comment by swashcap** [comment]
Here’s the remote result doc’s `data`:

``` json
{
   "currW": [
       227.365859307015,
       147.8106111546169,
       234.04290685641186
   ],
   "prevW": [
       227.365859307015,
       147.8106111546169,
       234.04290685641186
   ],
   "prevObjective": 4694312867.627573,
   "currObjective": 4694312867.627573,
   "eta": 0.1,
   "iteration": 151,
   "Gradient": [
       -38511924.15984652,
       45322.60020584179,
       -1025172.6176176445
   ],
   "lambda": 0,
   "Eg2": [
       1599375054654995,
       1867169107.947847,
       1103168747649.0425
   ],
   "EdW": [
       2.3512990164777765,
       2.8652509257408214,
       3.0029126750799238
   ],
   "rho": 0.5,
   "eps": 0.1,
   "deltaW": [
       1.5201230350517558,
       -1.7476415174771207,
       1.7259628888052772
   ]
}
```

**Comment by swashcap** [comment]
It would appear that _demo1_’s pipeline is out of sync. Its `data` corresponds with [the `preprocess` step](https://github.com/MRN-Code/decentralized-laplacian-ridge-regression/blob/06f324ccf9c41974300674e74664c3a5c260f993/src/local.js#L128-L133). However, the pipeline should use the `run` step at this point. _Interesting._
