### ISSUE TITLE
Make simulator output all errors

### ISSUE THREAD

**Issue by everner** [trendscenter/coinstac#870]
# Problem
When I run simulator without creating a docker image first, I don't see any error message telling me what the problem is. It just starts and stops quickly. When I used the `-x` flag, I was able to see the problem was no container. Given that this message is labeled as an error, I'm not sure why it would not be shown in the terminal.

```
URS6418EVERNER:coinstac-dpsvm everner$ coinstac-simulator
URS6418EVERNER:coinstac-dpsvm everner$ coinstac-simulator -x
debug:   Starting decentralized simulator run with 5 client(s)
silly:   Starting remote pipeline manager
silly:   File server up on port 3300
Mosca client connected remote_a24e606d
silly:   mqtt connection up remote
silly:   Starting local pipeline manager
Mosca client connected local0_00dcc56d
silly:   mqtt connection up local0
silly:   Starting local pipeline manager
silly:   Request to start service dpsvm
silly:   Starting service dpsvm at port: 8100
Mosca client connected local1_2c8e87af
silly:   mqtt connection up local1
silly:   Starting local pipeline manager
error:   unhandledRejection: Error: (HTTP code 404) no such container - No such image: dpsvm:latest 
    at /usr/local/lib/node_modules/coinstac-simulator/node_modules/docker-modem/lib/modem.js:257:17
    at getCause (/usr/local/lib/node_modules/coinstac-simulator/node_modules/docker-modem/lib/modem.js:287:7)
    at Modem.buildPayload (/usr/local/lib/node_modules/coinstac-simulator/node_modules/docker-modem/lib/modem.js:256:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/coinstac-simulator/node_modules/docker-modem/lib/modem.js:232:14)
    at iterateComp (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/controller.js:139:25)
    at iterateComp (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/controller.js:130:18)
    at Object.start (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/computation.js:39:12)
    at tryStartService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:458:15)
    at tryStartService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:277:10)
    at tryStartService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:233:10)
    at tryStartService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:227:10)
    at tryStartService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:197:10)
    at generateServicePort (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:1:1)
    at tryStartService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:196:14)
    at createService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:470:12)
    at Object.startService (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-docker-manager/src/index.js:492:10)
    at Object.start (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/computation.js:22:23)
    at iterateComp (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/controller.js:105:18)
    at Immediate.<anonymous> (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/controller.js:276:39)
    at _cb (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/controller.js:276:17)
    at /usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/controller.js:232:21
    at waterfall (/usr/local/lib/node_modules/coinstac-simulator/node_modules/coinstac-pipeline/src/controller.js:280:13)
```

# Tasks
Output all error messages from simulator in the terminal so that the user knows what the problem is.

**Comment by rssk** [comment]
Needs investigation, and in general sim's `blessed` ui is sort of a mess
